name: Build Flutter APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_apk:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v3
        with:
          flutter-version: '3.13.7'

      # 3. Get Flutter dependencies
      - name: Flutter pub get
        run: flutter pub get
        working-directory: ./mobile_app

      # 4. Build APK
      - name: Build APK
        run: flutter build apk --release
        working-directory: ./mobile_app

      # 5. Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MkulimaAI-APK
          path: mobile_app/build/app/outputs/flutter-apk/app-release.apk
